### ISSUE TITLE
Throwing things causes runtimes

### ISSUE THREAD

**Issue by Muncher2112** [Muncher2112/Interbay#1]
src: Khalil Best (/mob/living/carbon/human)
  src.loc: the floor (74,49,3) (/turf/simulated/floor/tiled)
  call stack:
  Khalil Best (/mob/living/carbon/human): throw item(the floor (74,49,3) (/turf/simulated/floor/tiled))
  Khalil Best (/mob/living/carbon/human): ClickOn(the floor (74,49,3) (/turf/simulated/floor/tiled), "icon-x=27;icon-y=15;left=1;scr...")
  /datum/click_handler/default (/datum/click_handler/default): OnClick(the floor (74,49,3) (/turf/simulated/floor/tiled), "icon-x=27;icon-y=15;left=1;scr...")
  the floor (74,49,3) (/turf/simulated/floor/tiled): Click(the floor (74,49,3) (/turf/simulated/floor/tiled), "mapwindow.map", "icon-x=27;icon-y=15;left=1;scr...")
  Muncher21 (/client): Click(the floor (74,49,3) (/turf/simulated/floor/tiled), the floor (74,49,3) (/turf/simulated/floor/tiled), "mapwindow.map", "icon-x=27;icon-y=15;left=1;scr...")

**Comment by Dekkar1218** [comment]
were you on the default utopia map when you did this test?

**Comment by Muncher2112** [comment]
Yes, on Utopia.  On the bridge, a few spaces away from the Magistrate's spawn.  I'll repro and post a screenshot when I get home

**Comment by Muncher2112** [comment]
Never mind, can't repro it.  Will open if it shows up again.
