### ISSUE TITLE
Stamnia run / walk not being utiilized correctly

### ISSUE THREAD

**Issue by Dekkar1218** [Muncher2112/Interbay#3]
#### Description of issue
Default mode is run when it should be walk, running should drain energy when toggled on - placeholder for energy already in game but not utilized (as far as I can see ) when energy is drained should receive an exhausted flag, maybe add some sound effects and screen effects to show tiredness. Experimenting with run / walk speeds for such purposes as well

**Comment by Muncher2112** [comment]
Closed with 22e98f6

**Comment by Muncher2112** [comment]
Want to add an overlay or at least message for when you <25% stamina
