### ISSUE TITLE
Skills and Stats 

### ISSUE THREAD

**Issue by Dekkar1218** [Muncher2112/Interbay#5]
#### Description of issue
Some jobs don't have skills, and vice versa at random. Stats and skills need to be revamped to be more meaningful, perhaps add in game ways to raise them during prolonged round times. Str and Dex should be combat related regarding dodging and parrying, basiclly needs to be more fleshed out

**Comment by Muncher2112** [comment]
If you have any specific actions or abilities that need checks or skills list them here.

**Comment by Dekkar1218** [comment]
Yes maybe the Parry or 2hand toggle could increase defence or offense respecticly. Maybe Parry uses skill checks where dodge would check Dex, Actions like grappling wrestling would check Str. For example if a player pins another player down, if other player tries to resist and get up does Str vs Str role.

**Comment by Dekkar1218** [comment]
sprinting / running should be able to longer / regen quicker if high dex etc

**Comment by Muncher2112** [comment]
~~NT effecting reading (pretty sure this already exists)~~
~~INT checks to crafting, or have it effect available recipes (Good time to refresh on crafting code)~~
~~INT checks to construction (possible recipes or failures)~~ Done with engineering checks
More checks for INT?

**Comment by Muncher2112** [comment]
~~Need to look over skills in general~~

~~Need to add checks for cooking and cleaning.  Crafting checks will come naturally as I look at the system more.~~

**Comment by Muncher2112** [comment]
Stats and skills are in a place where it's easy to quickly add checks for them, and all stats/skills are at least semi-relevant to current in-game content.  

I'm going to close this, but if anything specific comes to mind that needs a check, put it here
