### ISSUE TITLE
The Jukebox is broken

### ISSUE THREAD

**Issue by Muncher2112** [Muncher2112/Interbay#9]
#### Description of issue

I select a track and hit play, but don't hear any music.

#### Difference between expected and actual behavior

Would expect to hear music

#### Steps to reproduce 

use the jukebox

#### Specific information for locating

In the bar area

**Comment by Dekkar1218** [comment]
Could try repalcing old tracks with some rando's from some free sound website. (Shamelessly borrow tracks from Fallout and similiar games =-p)

**Comment by Muncher2112** [comment]
Blocked by https://github.com/Muncher2112/Interbay/issues/14

There's a 512 fix later in bay's jukebox code, which I'm assuming is borking this.
